### ISSUE TITLE
Traslados - Otras Salidas

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#10]
Ruta: /inventario/inventario/traslados

Al estar activa la opción "Otras Salidas", aparece activa la opción "proveedor de origen" y "proveedor nacional" están activos, cuando deberían de estar desactivados.

<a href='http://www.subirimagenes.com/privadas-5-2349894.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23498945.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Recibido

**Comment by suavid** [comment]
Resuelto
