### ISSUE TITLE
Traslados - Detalle de traslado

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#13]
Ruta:  /inventario/inventario/detalle_traslado

Se detecto un problema en el detalle de la compra, (operación 1b compras) a la hora de realizar un ingreso de mercadería, de esta forma:

Codigo: 101
Costo unitario previo: $10.00
Costo total Previo : $45.00

<a href='http://www.subirimagenes.com/privadas-81-2349907.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_234990781.png' alt='subir imagenes' border='0'></a>

Pares a ingresar: 5
Costo unitario a ingresar: $10.00
Costo total a ingresar: $50.00

<a href='http://www.subirimagenes.com/privadas-82-2349906.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_234990682.png' alt='subir imagenes' border='0'></a>

Al ingresar los el sistema se queda en esta ventana

<a href='http://www.subirimagenes.com/privadas-8-2349908.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23499088.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
¿Podrías volver a probar y decirme si te vuelve a dar el problema?, yo no pude replicar el problema, a mi me funcionó correctamente

**Comment by sperzero** [comment]
Voy a actualizar el código con las ultimas correcciones y voy a robar de nuevo.

**Comment by sperzero** [comment]
Confirmado, Caso puntual aislado.
