### ISSUE TITLE
Retaceo - General

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#14]
Ruta: /inventario/inventario/hoja_retaceo

Falta agregar como opción inicial sugerida el numero "cero" por defecto en el campo donde se declara si es un nuevo documento.

<a href='http://www.subirimagenes.com/privadas-1-2350709.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23507091.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Resuelto
