### ISSUE TITLE
Revision de salida - General

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#16]
Colocar un "combo" o similar en lugar del campo serie de factura.

<a href="http://subefotos.com/ver/?e67a57069a6f5d30c9dfd7dba9c1e925o.png" target="_blank"><img src="http://thumbs.subefotos.com/e67a57069a6f5d30c9dfd7dba9c1e925o.jpg" /></a>

**Comment by suavid** [comment]
Resuelto
