### ISSUE TITLE
Inventario - General

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#17]
Ruta /inventario/inventario/principal

Al presionar el botón de configuración (en la barra de navegación), aparece la palabra "METROUI"

<a href="http://subefotos.com/ver/?586cc4bc64f914a0caf8f7747ea8081do.png" target="_blank"><img src="http://thumbs.subefotos.com/586cc4bc64f914a0caf8f7747ea8081do.jpg" /></a>

**Comment by suavid** [comment]
Resuelto
