### ISSUE TITLE
Segmentación - Bodegas

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#19]
Ruta: /inventario/inventario/bodegas

Requerir permiso especial (podría ser una contraseña) para crear una bodega que no maneje stock (Esto es importante por temas de seguridad interna)

<a href='http://www.subirimagenes.com/privadas-5-2351501.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23515015.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Resuelto
