### ISSUE TITLE
Nuevo Producto - Documentos

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#21]
Ruta: /inventario/inventario/doc_productos?documento

Problemas al mostrar espacios en todo el formulario de documentos, es decir en los campos: proveedor, linea, catalogo, genero, marca, grupo, suela, concepto, material, propiedad.

Ejemplo:

<a href='http://www.subirimagenes.com/privadas-7-2351505.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23515057.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Resuelto
