### ISSUE TITLE
Campañas - General

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#22]
Ruta: /inventario/inventario/catalogos

Poner como valor predeterminado el numero "cero" como opción inicial en el campo "id catalogo"

Consulta 1: Cual es el peso máximo de la imagen a subir?
Consulta 2: Cuales son las dimensiones ideales que debe tener la imagen?

<a href='http://www.subirimagenes.com/privadas-8-2351506.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23515068.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Resuelto

No hay limite, pueden ser imágenes de alta calidad ya que se copian al servidor y no se guardan en la base de datos. El cuadro que aparece ahí ajustará el tamaño a un ancho fijo y la altura será variable para mantener el buen aspecto de la imagen.
