### ISSUE TITLE
Campañas - Nuevo 

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#23]
Ruta: /inventario/inventario/catalogos

La fecha final del catalogo es ingresa de manera automática cuando se ingresa un nuevo catalogo.

Ejemplo:

Si el día de hoy se inicia un nuevo catalogo (numero "2"), el sistema de manera automática, establece que el día de ayer termino el anterior (catalogo "1" ).

<a href='http://www.subirimagenes.com/privadas-9-2351508.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23515089.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Resuelto
