### ISSUE TITLE
Traslados - Ingreso por traslado

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#6]
al estar activa la opción Ingreso por traslado en las lineas, aparece activa la opción "proveedor de origen" y "proveedor nacional" están activos, cuando derivaran de estar desactivados.

<a href='http://www.subirimagenes.com/privadas-1-2349877.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23498771.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Enterado, lo revisare hoy en la noche

**Comment by suavid** [comment]
Resuelto
