### ISSUE TITLE
Traslados - Otros Ingresos

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#7]
Al estar activa la opción "Otros ingresos", aparece activa la opción "proveedor de origen" y "proveedor nacional" están activos, cuando deberían de estar desactivados.

<a href='http://www.subirimagenes.com/privadas-2-2349878.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23498782.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Recibido

**Comment by suavid** [comment]
Resuelto
