### ISSUE TITLE
Traslados - Devoluciones S/ Compras

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#8]
Ruta: /inventario/inventario/traslados

Al estar activa la opción "Devoluciones S/ Compras", aparece activa la opción "proveedor de origen" y "proveedor nacional" están activos, cuando deberían de estar desactivados.

<a href='http://www.subirimagenes.com/privadas-3-2349884.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23498843.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Recibido

**Comment by suavid** [comment]
Resuelto
