### ISSUE TITLE
Traslados - Salida por traslado

### ISSUE THREAD

**Issue by sperzero** [suavid/inventario#9]
Ruta: /inventario/inventario/traslados

Al estar activa la opción "Salida por traslado", aparece activa la opción "proveedor de origen" y "proveedor nacional" están activos, cuando deberían de estar desactivados.

<a href='http://www.subirimagenes.com/privadas-4-2349890.html'><img src='http://s2.subirimagenes.com/privadas/previo/thump_23498904.png' alt='subir imagenes' border='0'></a>

**Comment by suavid** [comment]
Recibido

**Comment by suavid** [comment]
Resuelto
